web/router.ex
defmodule Gebetsgruppe.Router do
  use Gebetsgruppe.Web, :router
  require Sentinel
  
  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  # This plug will look for a Guardian token in the session in the default location
  # Then it will attempt to load the resource found in the JWT.
  # If it doesn't find a JWT in the default location it doesn't do anything  
  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end
  
  # This pipeline is created for use within the admin namespace.
  # It looks for a valid token in the session - but in the 'admin' location of guardian
  # This keeps the session credentials seperate for the main site, and the admin site
  # It's very possible that a user is logged into the main site but not the admin
  # or it could be that you're logged into both.
  # This does not conflict with the browser_auth pipeline.
  # If it doesn't find a JWT in the location it doesn't do anything
  pipeline :admin_browser_auth do
    plug Guardian.Plug.VerifySession, key: :admin
    plug Guardian.Plug.LoadResource,  key: :admin
  end
  
  # We need this pipeline to load the token when we're impersonating.
  # We don't want to load the resource though, just verify the token
  pipeline :impersonation_browser_auth do
    plug Guardian.Plug.VerifySession, key: :admin
  end
  
  pipeline :api do
    plug :accepts, ["json"]
  end

  # This pipeline if intended for API requests and looks for the JWT in the "Authorization" header
  # In this case, it should be prefixed with "Bearer" so that it's looking for
  # Authorization: Bearer <jwt>
  pipeline :api_auth do
    plug Guardian.Plug.VerifyHeader, realm: "Bearer"
    plug Guardian.Plug.LoadResource
  end

  
  # Public Routes
  scope "/", Gebetsgruppe do
    # We pipe this through the browser_auth to fetch logged in people
    # We pipe this through the impersonation_browser_auth to know if we're impersonating
    # We don't just pipe it through admin_browser_auth because that also loads the resource
    pipe_through [:browser, :browser_auth, :impersonation_browser_auth]
        
    get "/",            PageController,   :index
    delete "/logout",   AuthController,   :logout
    
    get "/gebets",      GebetController,  :index
    get "/gebets/:id",  GebetController,  :show
    
    resources "/authorizations", AuthorizationController
    resources "/tokens",         TokenController
    resources "/users",          UserController

    get "/private",              PrivatePageController, :index
  end

  # This scope is the main authentication area for Ueberauth
  scope "/auth", Gebetsgruppe do
    pipe_through [:browser, :browser_auth] # Use the default browser stack

    get "/:identity",           AuthController, :login
    get "/:identity/callback",  AuthController, :callback
    post "/:identity/callback", AuthController, :callback
  end
  
  # This scope is intended for admin users.
  # Normal users can only go to the login page
  scope "/admin", Gebetsgruppe.Admin, as: :admin do
    pipe_through [:browser, :admin_browser_auth] # Use the default browser stack

    get "/login",                    SessionController, :new, as: :login
    get "/login/:identity",          SessionController, :new
    
    post   "/auth/:identity/callback", SessionController, :callback
    get    "/logout",                  SessionController, :logout
    delete "/logout",                  SessionController, :logout, as: :logout
    
    post   "/impersonate/:user_id", SessionController, :impersonate, as: :impersonation
    delete "/impersonate",          SessionController, :stop_impersonating

    resources "/users", UserController
  end
  
  # Private routes
  # scope "/", Gebetsgruppe do
  #   pipe_through [:browser, :browser_auth]
  #
  #   get  "/login",    SessionController, :new,    as: :login
  #   post "/login",    SessionController, :create, as: :login
  #
  #   delete "/logout", SessionController, :delete, as: :logout
  #   get    "/logout", SessionController, :delete, as: :logout
  #
  #   resources "/users", UserController
  # end
    
  # Public API
  scope "/api/v0", alias: Gebetsgruppe do
    pipe_through [:api]
      resources "/gebets", GebetController, only: [:index]

    Sentinel.mount
  end

  # Private API
  # scope "/api/v0", alias: Gebetsgruppe do
  #   pipe_through [:api, :api_auth]
  #     get "/gebets", GebetController, :index
  # end
  
end

web/views/admin/layout_view.ex
defmodule Gebetsgruppe.Admin.LayoutView do
  use Gebetsgruppe.Web, :view
end

web/views/layout_view.ex
defmodule Gebetsgruppe.LayoutView do
  use Gebetsgruppe.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Daryl Richter, Zaxonomy">

    <%= if Guardian.Plug.current_token(@conn) do %>
      <meta name="guardian_token" content="<%= Guardian.Plug.current_token(@conn) %>">
    <% end %>

    <title>Willkommen zu die Gebetsguppe!</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="uk-container uk-container-center uk-margin-top" role="main">
      <%= render "impersonation.html", conn: @conn %>
      <%= render "navigation.html", current_user: @current_user, conn: @conn %>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <%= render @view_module, @view_template, assigns %>
    </div>

    <!-- div class='row'>
      <div class="well text-center col-sm-6 col-xs-12 col-sm-offset-3">
        The socket says...
        <ul class="text-left list-unstlyed" id="socket-talk"></ul>
        <form id='socketForm' class='form form-horizontal' onsubmit='sendMessage(event)'>
          <div class='form-group col-sm-8'>
            <input class='form-control' placeholder='Enter your message…' name='message'/>
          </div>

          <div class='form-group col-sm-4'>
            <button class='btn btn-primary' id="send-message">Send</button>
          </div>
        </form>
      </div>
    </div -->
      
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/uikit.js") %>"></script>
  </body>
</html>

web/templates/layout/impersonation.html.eex
<%= if admin_logged_in?(@conn) && logged_in?(@conn) do %>
  <div class='impersonation-bar'>
    <%= link "Stop impersonating #{current_user(@conn).name}",
             to: admin_session_path(@conn, :stop_impersonating),
             method: "DELETE",
             class: "btn btn-xs btn-warning"
    %>
  </div>
<% end %>

web/templates/layout/navigation.html.eex
<nav class="uk-navbar">
  <a class="uk-navbar-brand" href="/"><i class="uk-icon-home uk-icon-small"></i></a>
  
  <%= if @current_user do %>
    <ul class="uk-navbar-nav">
      <li class="<%= active_on_current(@conn, gebet_path(@conn, :index)) %>">
        <%= link "Prayers", to: gebet_path(@conn, :index) %>
      </li>

      <li class="uk-parent" data-uk-dropdown aria-haspopup="true" aria-expanded="false">
        <a href="">My Stuff <i class="uk-icon-caret-down"></i></a>
        <div class="uk-dropdown uk-dropdown-navbar uk-dropdown-bottom" style="top: 40px; left: 0px;">
          <ul class="uk-nav uk-nav-navbar">
            <li><%= link "Private", to: private_page_path(@conn, :index) %></li>
            <li>
              <%= link "Authorizations", to: authorization_path(@conn, :index) %>
            </li>
            <li>
              <%= link "Tokens", to: token_path(@conn, :index) %>
            </li>
          </ul>
        </div>
      </li>

      <%= if @conn.request_path != auth_path(@conn, :login, "identity") do %>
        <li class="<%= active_on_current(@conn, authorization_path(@conn, :index)) %>">
          <%= link "Connect", to: auth_path(@conn, :login, "identity") %>
        </li>
      <% end %>

      <li class="<%= active_on_current(@conn, authorization_path(@conn, :index)) %>">
        <%= link "Logout", to: auth_path(@conn, :logout), method: :delete %>
      </li>
    </ul>
  <% else %>
    <ul class="uk-navbar-nav uk-hidden-small uk-navbar-flip">
      <li class="uk-active">
        <%= if @conn.request_path != auth_path(@conn, :login, "identity") do %>
          <%= link "Login", to: auth_path(@conn, :login, "identity") %>
        <% end %>
      </li>
    </ul>
  <% end %>
  
</nav>